
#           /$$$$$$                                      /$$                               /$$$$$$$
#          /$$__  $$                                    | $$                              | $$__  $$
#         | $$  \__/  /$$$$$$   /$$$$$$   /$$$$$$   /$$$$$$$  /$$$$$$  /$$   /$$ /$$$$$$$ | $$  \ $$  /$$$$$$   /$$$$$$$  /$$$$$$$
#         |  $$$$$$  /$$__  $$ /$$__  $$ /$$__  $$ /$$__  $$ /$$__  $$| $$  | $$| $$__  $$| $$$$$$$  /$$__  $$ /$$_____/ /$$_____/
#          \____  $$| $$  \ $$| $$$$$$$$| $$$$$$$$| $$  | $$| $$  \__/| $$  | $$| $$  \ $$| $$__  $$| $$  \ $$|  $$$$$$ |  $$$$$$
#          /$$  \ $$| $$  | $$| $$_____/| $$_____/| $$  | $$| $$      | $$  | $$| $$  | $$| $$  \ $$| $$  | $$ \____  $$ \____  $$
#         |  $$$$$$/| $$$$$$$/|  $$$$$$$|  $$$$$$$|  $$$$$$$| $$      |  $$$$$$/| $$  | $$| $$$$$$$/|  $$$$$$/ /$$$$$$$/ /$$$$$$$/
#         \______/ | $$____/  \_______/ \_______/ \_______/|__/       \______/ |__/  |__/|_______/  \______/ |_______/ |_______/  by Drygo
#                  | $$
#                  | $$           Github repository: https://github.com/xDrygo/SpeedrunBoss - X: https://x.com/eldrygo
#                  |__/

# Welcome to the config file of SpeedrunBoss plugin! In the messages.yml file you can modify the plugin messages.

settings:
  wither_skull_multiplier: 2.0 #The multiplier of the wither skull drop probability.
  pvp_start_delay: 400 #In Ticks
  graceperiod_duration: 200 #In ticks
  cinematics:
    bypass:
      enabled: true
      list:
        - xDrygo
teams:
  red:
    members:
      - player1
      - player2
    displayName: '&e&lRed Team'
    priority: 2
  yellow:
    members:
      - player5
      - player6
    displayName: '&e&lYellow Team'
    priority: 0
  blue:
    members:
      - player3
      - player4
    displayName: '&e&lBlue Team'
    priority: 1