#           /$$$$$$                                      /$$                               /$$$$$$$
#          /$$__  $$                                    | $$                              | $$__  $$
#         | $$  \__/  /$$$$$$   /$$$$$$   /$$$$$$   /$$$$$$$  /$$$$$$  /$$   /$$ /$$$$$$$ | $$  \ $$  /$$$$$$   /$$$$$$$  /$$$$$$$
#         |  $$$$$$  /$$__  $$ /$$__  $$ /$$__  $$ /$$__  $$ /$$__  $$| $$  | $$| $$__  $$| $$$$$$$  /$$__  $$ /$$_____/ /$$_____/
#          \____  $$| $$  \ $$| $$$$$$$$| $$$$$$$$| $$  | $$| $$  \__/| $$  | $$| $$  \ $$| $$__  $$| $$  \ $$|  $$$$$$ |  $$$$$$
#          /$$  \ $$| $$  | $$| $$_____/| $$_____/| $$  | $$| $$      | $$  | $$| $$  | $$| $$  \ $$| $$  | $$ \____  $$ \____  $$
#         |  $$$$$$/| $$$$$$$/|  $$$$$$$|  $$$$$$$|  $$$$$$$| $$      |  $$$$$$/| $$  | $$| $$$$$$$/|  $$$$$$/ /$$$$$$$/ /$$$$$$$/
#         \______/ | $$____/  \_______/ \_______/ \_______/|__/       \______/ |__/  |__/|_______/  \______/ |_______/ |_______/  by Drygo
#                  | $$
#                  | $$           Github repository: https://github.com/xDrygo/SpeedrunBoss - X: https://x.com/eldrygo
#                  |__/

# Welcome to the config file of SpeedrunBoss plugin! In the messages.yml file you can modify the plugin messages.

settings:
  wither_skull_multiplier: 2.0 # The multiplier of the wither skull drop probability.
  pvp_start_delay: 24000 # In Ticks
  graceperiod_duration: 6000 # In ticks
  compass_search_radius: 1000
  team_radius_to_bossregister: 30.0
  cinematics:
    bypass:
      enabled: true
      list:
        - xDrygo
  waiting_screen:
    bypass:
      enabled: true
      list:
        - xDrygo
teams:
  team_4:
    members:
      - Master62_
      - SoyPepon
    displayName: ओ
    priority: 4
  team_17:
    members:
      - FraxterYT
      - imDarh
    displayName: ठ
    priority: 17
  team_2:
    members:
      - CrisNow2k
      - Minerexking
    displayName: ऑ
    priority: 2
  team_12:
    members:
      - 4quiles
      - TheYeiYT
    displayName: छ
    priority: 12
  team_6:
    members:
      - LastGodGG
      - SrpSeba
    displayName: क
    priority: 6
  team_14:
    members:
      - Javierixmon
      - OOKAMIIVT
    displayName: झ
    priority: 14
  team_9:
    members:
      - LaKpi
      - OwencinNashe_
    displayName: घ
    priority: 9
  team_7:
    members:
      - BurritoRiv
      - DarkWitch
    displayName: ख
    priority: 7
  team_5:
    members:
      - SoyNilo
      - FerGRDC
    displayName: औ
    priority: 5
  team_3:
    members:
      - VictormvvOficial
      - Flycken12
    displayName: ऒ
    priority: 3
  team_10:
    members:
      - ELAPRHttv
      - OsvaGamer
    displayName: ङ
    priority: 10
  team_13:
    members:
      - AimSunny
      - bemnja
    displayName: ज
    priority: 13
  team_16:
    members:
      - Nicole077
      - Khipa
    displayName: ट
    priority: 16
  team_1:
    members:
      - Fepo5302
      - FrannCano
    displayName: ऐ
    priority: 1
  staff:
    members:
      - xDrygo
    displayName: ं
    priority: 99
  team_8:
    members:
      - DaniTrembl4y
      - Limonxrd
    displayName: ग
    priority: 8
  team_15:
    members:
      - KansuDeAsura
      - AsuraDKansu
    displayName: ञ
    priority: 15
  team_11:
    members:
      - Morbux
      - Santiibuxi
    displayName: च
    priority: 11