name: SpeedrunBoss
main: org.eldrygo.SpeedrunBoss
version: 0.0.01
api-version: 1.21
authors: [Drygo]
depend:
  - PlaceholderAPI
  - Vault
  - xTeams
commands:
  speedrunboss:
    aliases:
      - spb
      - sboss
    description: "SpeedrunBoss plugin main command."
permissions:
  spb.compass:
    description: "Permission to use the compass features."
    default: false
    children:
      spb.compass.give:
        description: "Permission to use /spb compass give command."
        default: false
      spb.compass.admin:
        description: "Permission to use all compass features."
        default: false
  spb.admin:
    description: "Permission to execute commands related to SpeedrunBoss."
    default: false